version: "3.8"

services:
  v10:
    image: felddy/foundryvtt:10
    hostname: my_foundry_host
    init: true
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - FOUNDRY_PASSWORD
      - FOUNDRY_USERNAME
      - CONTAINER_PRESERVE_CONFIG
    ports:
      - target: 30000
        published: 30000
        protocol: tcp

  v11:
    image: felddy/foundryvtt:11.302
    hostname: my_foundry_host
    init: true
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - FOUNDRY_PASSWORD
      - FOUNDRY_USERNAME
      - CONTAINER_PRESERVE_CONFIG
    ports:
      - target: 30000
        published: 30000
        protocol: tcp